Traceback (most recent call last):
  File "c:\anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "c:\anaconda3\lib\site-packages\nbclient\client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "c:\anaconda3\lib\site-packages\nbclient\util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "c:\anaconda3\lib\site-packages\nbclient\util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "c:\anaconda3\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "c:\anaconda3\lib\site-packages\nbclient\client.py", line 541, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "c:\anaconda3\lib\site-packages\nbclient\client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "c:\anaconda3\lib\site-packages\nbclient\client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Determina si una serie de enteros son primos.

while True:
    try:
        numero = int(input('Deme un entero positivo mayor que 1: '))
        if numero < 2:
            raise ValueError('El valor introducido debe ser mayor que 1.')
    except ValueError as e:
        print(e)
    else:
        es_primo = True
        for div in range(2, numero):
            if numero % div == 0:
                es_primo = False
                break
        if es_primo:
            print("El nÃºmero {} es primo.".format(numero))
        else:
            print("El nÃºmero {} no es primo.".format(numero))
    finally:
        opcion = input("Desea salir (s/n):")
        if opcion == 's' or opcion == 'S':
            break
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mStdinNotImplementedError[0m                  Traceback (most recent call last)
[1;32m<ipython-input-1-acb7770ad0eb>[0m in [0;36m<module>[1;34m[0m
[0;32m      4[0m     [1;32mtry[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m----> 5[1;33m         [0mnumero[0m [1;33m=[0m [0mint[0m[1;33m([0m[0minput[0m[1;33m([0m[1;34m'Deme un entero positivo mayor que 1: '[0m[1;33m)[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      6[0m         [1;32mif[0m [0mnumero[0m [1;33m<[0m [1;36m2[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m

[1;32mC:\Anaconda3\lib\site-packages\ipykernel\kernelbase.py[0m in [0;36mraw_input[1;34m(self, prompt)[0m
[0;32m    857[0m             raise StdinNotImplementedError(
[1;32m--> 858[1;33m                 [1;34m"raw_input was called, but this frontend does not support input requests."[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    859[0m             )

[1;31mStdinNotImplementedError[0m: raw_input was called, but this frontend does not support input requests.

During handling of the above exception, another exception occurred:

[1;31mStdinNotImplementedError[0m                  Traceback (most recent call last)
[1;32m<ipython-input-1-acb7770ad0eb>[0m in [0;36m<module>[1;34m[0m
[0;32m     19[0m             [0mprint[0m[1;33m([0m[1;34m"El nÃºmero {} no es primo."[0m[1;33m.[0m[0mformat[0m[1;33m([0m[0mnumero[0m[1;33m)[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m     20[0m     [1;32mfinally[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m---> 21[1;33m         [0mopcion[0m [1;33m=[0m [0minput[0m[1;33m([0m[1;34m"Desea salir (s/n):"[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m     22[0m         [1;32mif[0m [0mopcion[0m [1;33m==[0m [1;34m's'[0m [1;32mor[0m [0mopcion[0m [1;33m==[0m [1;34m'S'[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m     23[0m             [1;32mbreak[0m[1;33m[0m[1;33m[0m[0m

[1;32mC:\Anaconda3\lib\site-packages\ipykernel\kernelbase.py[0m in [0;36mraw_input[1;34m(self, prompt)[0m
[0;32m    856[0m         [1;32mif[0m [1;32mnot[0m [0mself[0m[1;33m.[0m[0m_allow_stdin[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m    857[0m             raise StdinNotImplementedError(
[1;32m--> 858[1;33m                 [1;34m"raw_input was called, but this frontend does not support input requests."[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    859[0m             )
[0;32m    860[0m         return self._input_request(str(prompt),

[1;31mStdinNotImplementedError[0m: raw_input was called, but this frontend does not support input requests.
StdinNotImplementedError: raw_input was called, but this frontend does not support input requests.

